In [1]:
# Importing Libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import math

In [2]:
Rain_train = pd.read_csv('Data/test.csv')
Rain_train.head(3)

,id,day,pressure,maxtemp,temparature,mintemp,dewpoint,humidity,cloud,sunshine,winddirection,windspeed
0,2190,1,1019.5,17.5,15.8,12.7,14.9,96.0,99.0,0.0,50.0,24.3
1,2191,2,1016.5,17.5,16.5,15.8,15.1,97.0,99.0,0.0,50.0,35.3
2,2192,3,1023.9,11.2,10.4,9.4,8.9,86.0,96.0,0.0,40.0,16.9

In [3]:
Rain_train['maxt-dew'] = Rain_train['maxtemp']- Rain_train['dewpoint']

In [4]:
Rain_train['cloud_humidity'] = Rain_train['cloud']*Rain_train['humidity']

In [5]:
Rain_train['cloud_humidity/Press']= Rain_train['cloud_humidity']/Rain_train['pressure']

In [6]:
Rain_train['clo^2'] =  Rain_train['cloud']**2

In [7]:
Rain_train['wi'] = (0.4*Rain_train['humidity'])+ (0.3*Rain_train['cloud'])-(0.3*Rain_train['sunshine'])

In [8]:
Rain_train['sun_humidity'] = Rain_train['sunshine']/Rain_train['humidity']

In [9]:
# Rain_train['lluvia'] = Rain_train['rainfall']

In [10]:
Rain_train_Feature = Rain_train.drop(['day','pressure','temparature','mintemp',
                                      'winddirection'], axis=1)

In [11]:
Rain_train_Feature.to_csv('Data/Te.Feature.2.Rain.csv', index=False)

In [12]:
Rain_train_Feature

,id,maxtemp,dewpoint,humidity,cloud,sunshine,windspeed,maxt-dew,cloud_humidity,cloud_humidity/Press,clo^2,wi,sun_humidity
0,2190,17.5,14.9,96.0,99.0,0.0,24.3,2.6,9504.0,9.322217,9801.0,68.10,0.000000
1,2191,17.5,15.1,97.0,99.0,0.0,35.3,2.4,9603.0,9.447122,9801.0,68.50,0.000000
2,2192,11.2,8.9,86.0,96.0,0.0,16.9,2.3,8256.0,8.063287,9216.0,63.20,0.000000
3,2193,20.6,9.5,75.0,45.0,7.1,50.6,11.1,3375.0,3.299443,2025.0,41.37,0.094667
4,2194,16.1,4.3,68.0,49.0,9.2,19.4,11.8,3332.0,3.259636,2401.0,39.14,0.135294
...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,2915,18.2,13.7,96.0,95.0,0.0,34.3,4.5,9120.0,8.934169,9025.0,66.90,0.000000
726,2916,23.2,16.0,78.0,80.0,1.6,25.2,7.2,6240.0,6.167836,6400.0,54.72,0.020513
727,2917,21.0,15.5,92.0,96.0,0.0,21.9,5.5,8832.0,8.635964,9216.0,65.60,0.000000
728,2918,21.0,19.8,94.0,93.0,0.0,39.5,1.2,8742.0,8.617902,8649.0,65.50,0.000000
729,2919,22.2,13.3,79.0,89.0,0.2,50.6,8.9,7031.0,6.887060,7921.0,58.24,0.002532