# Third approach

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from warnings import filterwarnings

filterwarnings("ignore")

In [3]:
Rain_train = pd.read_csv('Data/train.csv')
Rain_test = pd.read_csv('Data/test.csv')

display(Rain_train.head(4))
display(Rain_test.head(4))

,id,day,pressure,maxtemp,temparature,mintemp,dewpoint,humidity,cloud,sunshine,winddirection,windspeed,rainfall
0,0,1,1017.4,21.2,20.6,19.9,19.4,87.0,88.0,1.1,60.0,17.2,1
1,1,2,1019.5,16.2,16.9,15.8,15.4,95.0,91.0,0.0,50.0,21.9,1
2,2,3,1024.1,19.4,16.1,14.6,9.3,75.0,47.0,8.3,70.0,18.1,1
3,3,4,1013.4,18.1,17.8,16.9,16.8,95.0,95.0,0.0,60.0,35.6,1

,id,day,pressure,maxtemp,temparature,mintemp,dewpoint,humidity,cloud,sunshine,winddirection,windspeed
0,2190,1,1019.5,17.5,15.8,12.7,14.9,96.0,99.0,0.0,50.0,24.3
1,2191,2,1016.5,17.5,16.5,15.8,15.1,97.0,99.0,0.0,50.0,35.3
2,2192,3,1023.9,11.2,10.4,9.4,8.9,86.0,96.0,0.0,40.0,16.9
3,2193,4,1022.9,20.6,17.3,15.2,9.5,75.0,45.0,7.1,20.0,50.6

### Preparing new features

In [ ]:
def FE(data):
    df = data.copy()

    # Temperature Features
    df['temp_gap'] = df['maxtemp'] - df['mintemp']
    df['dewpoint_depression'] = df['temparature'] - df['dewpoint']

    # Wind Features
    df['wind_power'] = df['windspeed'] ** 3
    
    # Cloud & Humidity Features
    df['cloud_rolling_avg'] = df['cloud'].rolling(window=3, min_periods=1).mean().fillna(method='bfill')
    df['humidity_cloud_interaction'] = df['humidity'] * df['cloud']
    #df['dewpoint_humidity_interaction'] = df['dewpoint'] * df['humidity']
    
    # Extreme Weather Flags
    #df['high_wind_flag'] = (df['windspeed'] >= 40).astype(int)

    # Drop Unimportant Columns
    df.drop(columns=['day', 'winddirection', 'pressure', 'mintemp', 'temparature'], inplace=True)
    
    return df